### ISSUE TITLE
Create a Dockerfile

### ISSUE THREAD

**Issue by BenjaminN117** [BenjaminN117/UOS_Website_Project#6]
Create a Dockerfile that runs the website in a container. 

P.S If your unsure about Docker, Google it!

**Comment by probro27** [comment]
@BenjaminN117 Please assign me this issue. I can work on this. 
Just want to confirm
Do you want me place the Dockerfile in the root directory or in the src/submissions as per 
**Please add your answers to the "src/submissions" directory with the filename "UOS_ID-ISSUE_NAME.html"**

**Comment by BenjaminN117** [comment]
Hey @probro27 could you place it in the root directory pls
